spring.datasource.url=jdbc:postgresql://localhost:5432/mealplanner
spring.datasource.username=postgres
spring.datasource.password=20040830S
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-1.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiry-ms=86400000

server.port=8080

logging.level.com.aimealplan.senseai=DEBUG